@echo off
@echo 1
.\DotsAndBoxes.exe .\settings\settings3_1.json
@echo 2
.\DotsAndBoxes.exe .\settings\settings3_2.json
@echo 3
.\DotsAndBoxes.exe .\settings\settings3_3.json
@echo 4
.\DotsAndBoxes.exe .\settings\settings3_4.json
@echo 5
.\DotsAndBoxes.exe .\settings\settings3_5.json
@echo 6
.\DotsAndBoxes.exe .\settings\settings3_6.json